// sveltekit/src/lib/TemperatureConverter.svelte
<script lang="ts">
	let c: number;
	let f: number;
	function handleCelsius() {
		if (isNaN(c)) return;
		f = c * (9 / 5) + 32;
	}
	function handleFahrenheit() {
		if (isNaN(f)) return;
		c = (f - 32) * (5 / 9);
	}
</script>

<label>
	<input bind:value={c} on:input={handleCelsius} />
	Celsius
</label>
=
<label>
	<input bind:value={f} on:input={handleFahrenheit} />
	Fahrenheit
</label>

// nuxt/components/TemperatureConverter.vue
<script setup lang="ts">
import { ref } from 'vue';
const c = ref<number>(undefined);
const f = ref<number>(undefined);
function handleCelsius() {
	if (isNaN(c.value)) return;
	f.value = c.value * (9 / 5) + 32;
}
function handleFahrenheit() {
	if (isNaN(f.value)) return;
	c.value = (f.value - 32) * (5 / 9);
}
</script>
<template>
	<label>
		<input v-model="c" @input="handleCelsius" />
		Celsius
	</label>
	=
	<label>
		<input v-model="f" @input="handleFahrenheit" />
		Fahrenheit
	</label>
</template>
