// src/components/lib/TemperatureConverter.tsx
import { ChangeEvent, useState } from 'react';
export default function () {
	const [c, setC] = useState<number | string>('');
	const [f, setF] = useState<number | string>('');
	function handleCelsius(e: ChangeEvent<HTMLInputElement>) {
		const value = e.target.value;
		setC(value);
		if (isNaN(+value)) return;
		setF(+value * (9 / 5) + 32);
	}
	function handleFahrenheit(e: ChangeEvent<HTMLInputElement>) {
		const value = e.target.value;
		setF(value);
		if (isNaN(+value)) return;
		setC((+value - 32) * (5 / 9));
	}
	return (
		<>
			<label>
				<input value={c} onInput={handleCelsius} />
				Celsius
			</label>
			=
			<label>
				<input value={f} onInput={handleFahrenheit} />
				Fahrenheit
			</label>
		</>
	);
}

// astro/src/components/lib/TemperatureConverter.vue
<script setup lang="ts">
const c = ref<number>(undefined);
const f = ref<number>(undefined);
function handleCelsius() {
	if (isNaN(c.value)) return;
	f.value = c.value * (9 / 5) + 32;
}
function handleFahrenheit() {
	if (isNaN(f.value)) return;
	c.value = (f.value - 32) * (5 / 9);
}
</script>
<template>
	<label>
		<input v-model="c" @input="handleCelsius" />
		Celsius
	</label>
	=
	<label>
		<input v-model="f" @input="handleFahrenheit" />
		Fahrenheit
	</label>
</template>
